name: CI Pipeline

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:
    branches:
      - dev
      - test
      - main

jobs:
  lint:
    name: ES-Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Run ES-Lint
        run: bun run lint

  build:
    name: Build Next.js Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build Next.js
        run: bun run build
        
  cloudflare-simulation:
    name: Simulate Cloudflare Pages Environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image for Cloudflare simulation
        run: |
          docker build -t cloudflare-pages-sim -f ./Dockerfile.cloudflare .
                    
      - name: Run deployment simulation in Docker
        run: |
          docker run --rm -v ${PWD}:/app cloudflare-pages-sim
          
      - name: Output simulation logs
        run: |
          echo "Cloudflare Pages simulation completed"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"